### ISSUE TITLE
Remember setting to not synchronize a certain workspace

### ISSUE THREAD

**Issue by ajkauffmann** [vjekob/al-objid#10]
In an individual workspace, you will get a popup 'Do you want to synchronize' every time when using ctrl+space to get an object id. It doesn't remember when I click No.

Could it remember that I don't want to use Object ID Ninja in a particular workspace?

**Comment by waldo1001** [comment]
*Just Sync*¨🤪

**Comment by ajkauffmann** [comment]
Why would I do that?

**Comment by waldo1001** [comment]
Why not?

**Comment by waldo1001** [comment]
Ah .. yeah .. that makes sense 😉

**Comment by vjekob** [comment]
From my perspective, it's pointless to have Ninja remember that you don't want to use it in a workspace. That's what VS Code already does, and it's called "Disable (Workspace)" and you can choose which extensions are enabled or disabled per workspace. So - if you don't want Ninja to monitor an app, just disable it for that app.

Furthermore, you can maybe already see in the code that Ninja will only ask you once to synchronize. Then it will remember your choice of "No" and won't bug you for the duration of that VS Code session. This is not yet released, because I have some minor things I want to do around it, but it's coming.

However, I don't think why you would both want to have Ninja enabled for an extension and have it not do its job. Either you enable it, sync, and use it, or you disable it and live happily ever after. But you *do* have this choice already.

Do you agree?

**Comment by ajkauffmann** [comment]
I see your point, didn't think about disabling / enabling it. Makes sense!
But I would rather do it the other way around. Disable it globally and enable it per app. That's less work 😉

**Comment by vjekob** [comment]
Either way, it's something VS Code already allows you to control.

I'll do some final touches to asking this nagging question, and then let it stay as is.

**Comment by vjekob** [comment]
There, I've just published version 1.2.1 - it fixes this.

I am closing this issue, if you think we need to talk more about it, let me know and I'll reopen.
