### ISSUE TITLE
(Nice to Have) Alternative search name for VS Code commands?

### ISSUE THREAD

**Issue by fvet** [vjekob/al-objid#13]
Although I like the name '**vjeko**', I'm often tempted to search for VS Code commandlets by their extensions name, but can't find anything for '**Ninja**'. Is there an option in VS Code to set an alternative search name, allowing to search for vjeko / ninja / object id?

![image](https://user-images.githubusercontent.com/25268332/134797208-98b37556-3815-4c7b-a563-c9f18eb57d67.png)

**Comment by vjekob** [comment]
You are right. It should actually be "Ninja" rather than "Vjeko". It's confusing (and a bit narcissistic, too 😁)

Thing is, I actually wanted to name extension "Vjeko Object ID *something or other*" but then decided to not use "Vjeko" in extension name. Apparently, I forgot to update the command names.

It's not an easy change now, actually... Unfortunately, the existing documentation is full of screenshots and animations where "Vjeko: ..." is used, so I'd have to re-take all those screenshots and re-record all those animations, and that's a lot of (probably unnecessary) work.

I'll most likely simply add aliases...
