### ISSUE TITLE
Automatic detection of object deletion and automatic releasing of freed-up object IDs

### ISSUE THREAD

**Issue by tboudrezMprise** [vjekob/al-objid#26]
Hi Vjeko,

In the Overview of AL Object Ninja on the Marketplace there has been this text for a while now:

_Note: Automatic detection of object deletion and automatic releasing of freed-up object IDs is currently in development and will be included in the next version._

A new version has now been released, but I don't see this functionality in the change log. When will this be released?

Thank you in advance!

**Comment by vjekob** [comment]
Hi tboudrezMprise,

The description in Marketplace simply gave some ideas of features I want to work on. This particular feature is in my backlog and I will deliver it when I get around to it. There is no promise in the description of *when* something is coming, just *what* is coming in the future.

I hope you understand this is my hobby project that I do on my own spare time for free. That's why I cannot commit to any firm timeline about anything.

/Vjeko
