### ISSUE TITLE
Create a simple App Pool: Cannot read properties of undefined

### ISSUE THREAD

**Issue by pzentner** [vjekob/al-objid#39]
I am trying to work in the same workspace as defined in #36 right now and I do see some changes to the behavior of Object Ninja. For instance, the command "Copy ranges from app.json to .objidconfig works. I am using the exact same folder structure and workspace file as described before.

However, when I try to use "Create a simple App Pool", I am getting the error "Cannot read properties of undefined (reading 'manifest')". I would assume that it means that it can't find the objidconfig, but not sure. Based on this assumption, however, I have played a bit with having different files open thinking, I would be able to force the system to use the right paths. Didn't work though.

I also have tried to change the encoding of the app.json file to UTF-8, but this didn't do anything either.

Not sure, if you want me to open an additional issue, but I also tested the "Authorize App" for the test app (second app in the workspace) and while it doesn't throw an error, it doesn't add anything to the .objidconfig, so I am assuming it also can't find it. However, in all of those tests, the proper "active app" is shown in the status bar.

**Comment by paulojcdev** [comment]
Hi @vjekob , did you release the 2.9.2? 
I have 2.9.1 and don't see a .2 and I'm getting this error.

Thanks

**Comment by vjekob** [comment]
Yeah, it's not yet released - sorry for this. Working on it.

**Comment by jwikman** [comment]
@vjekob what happened with v2.9.2? 😅

We are suffering from this bug as well.

**Comment by jwikman** [comment]
Just for anyone that suffer from this and do not want to wait for v2.9.2:

This seems occur if there are a non-AL App workspace folder in the workspace.
We have a workspace folder with our pipelines files, and temporarily removing that from the workspace (and committing, since "Authorize App" does not work on "dirty" git repos) made it possible to run "Authorize App" on the workspace. Afterwards I reverted the temporary commit to get our pipeline folder back. :)

**Comment by vjekob** [comment]
2.9.2 has just been released. Sincere appologies to everyone for waiting this long.
