### ISSUE TITLE
Bug: license check doesn't check temporary tables

### ISSUE THREAD

**Issue by waldo1001** [vjekob/al-objid#40]
Temporary tables does not need to be in the license..
![image](https://user-images.githubusercontent.com/12088142/173860546-fec55feb-b87e-410c-9066-24fdd2779b37.png)

**Comment by vjekob** [comment]
Yeah, this is a bug. I'll look into this.

**Comment by pri-kise** [comment]
@vjekob I'd really like to get this fixed with a pull request, but I couldn't find the information in your "semi-private" repository of your AL-Types / AL Parser what properties are stored in the ALObject Class.

https://github.com/vjekob/al-objid/blob/08a794c399e253ece9a82f9c769eab874d59e258/vscode-extension/src/lib/BCLicense.ts#L57

If the TableType is included in some generic property then it shouldn't be to difficult so skip the error at this position:
https://github.com/vjekob/al-objid/blob/08a794c399e253ece9a82f9c769eab874d59e258/vscode-extension/src/lib/BCLicense.ts#L69

**Comment by vjekob** [comment]
Fixed in release 2.10.0 (to be released this week)
