### ISSUE TITLE
Check Object ID's against a Customer license

### ISSUE THREAD

**Issue by louagej** [vjekob/al-objid#5]
Hi @vjekob ,

First of all thank you for this cool VSCode extension.

I just imagined that it could be useful that there should be a warning if an new object is not in the customers license.
Sometimes this problem only arises when the new feature request is already in the test-environment of the customer and creates an awkward situation where the customer is informed to buy ore objects while testing it's new feature.

Regards,
Job

**Comment by pzentner** [comment]
While I agree that this might make sense, typically this should be found during testing as you should either tun your automated or at least manual tests against the customers license before delivery to customer

**Comment by louagej** [comment]
@pzentner,

I agree (partially), you can receive a notification or error when something's wrong with the object range depending on you customers license.
but personally would prefer being noticed before any build pipeline is fired on Azure where also a test app is being deployed.

It's just a waste of time and resources being informed afterwards.
After all, this always return like a boomerang to a developer.

**Comment by pzentner** [comment]
@louagej 

You are absolutely correct, it would be nice to have it caught earlier and we are also still debating different solutions on how to do this the best way for any customer specific additions we are adding (we are trying to avoid them like the plague, but can't always).

I am basically saying that I don't know, if this extension is the right way of solving the issue, especially when you want to support different scenarios. For instance, I can see this working (e.g. with using the detailed report that you can download) and have it parse against it. This could be done in here, but it could also be another service or module that you can use to test locally, but also run it through the pipeline so that you can test in different ways. If you have it in here, then this would have to be exposed from the backend to your pipeline so that you can test it as well during your build (so that it only tests the app and not the test app, which would then be run during the test pipeline).

**Comment by vjekob** [comment]
Just to chip in, this is an interesting suggestion. I'm keeping it open, and I'll handle it at some point (I have some other more urgent things).

Pull requests are always welcome, also 😉

**Comment by vjekob** [comment]
Completed in v2.5.0.

Check the release notes here: https://github.com/vjekob/al-objid/blob/master/vscode-extension/docs/ReleaseNotes.v2.5.0.md

**Comment by louagej** [comment]
@vjekob ,
thanks for that!
:star::star::star::star::star:
