### ISSUE TITLE
Synchronize Object Ids with Azure Backend - permissionsets

### ISSUE THREAD

**Issue by bcarmo-dev** [vjekob/al-objid#53]
Hi,

I think there's an issue when synchronizing the object ids with the azure backend. When I try to sync everything, I think that permissionsets are not being synced.

**1 step:
I create a new permissionset without using the Intellisense** 
![image](https://user-images.githubusercontent.com/95182940/208458961-df41c12c-bd18-4e93-9359-83b42040d0fb.png)

**2 step:
I sync all the objects using replace**
![image](https://user-images.githubusercontent.com/95182940/208461506-085d98ad-1a8c-4b44-84dc-463ce7627819.png)

**3 step:
When I request a new id for permission set, AL Object Id Ninja will suggest again the 50100**
![image](https://user-images.githubusercontent.com/95182940/208460829-9e3716f0-7046-4d40-a936-dea4bb51e023.png)

I don't know if I'm doing something wrong, or missing something or if there's indeed a bug.

**Comment by vjekob** [comment]
Sorry, I can't repeat this. I have just tried syncing permissionsets and it syncs them correctly. I tried having invalid content inside (because your example seems to not be accepted by AL compiler), but Ninja still synchronized the permissionset object IDs correctly.

I would suggest upgrading to latest version of Ninja.

If the problem still persists, please give me the exact copy of your permission set object as text (I can't copy text from screenshots), and I'll reopen the issue if it can be repeated.
