### ISSUE TITLE
Problems reported in VSC do not follow standard

### ISSUE THREAD

**Issue by TCI-Radek** [vjekob/al-objid#61]
Hi,

While the fact to have problems from Object Ninja (N0301) reported among others is super nice - they are not being handled as other codes - meaning: we cannot suppress them in app.json or escalate them in ruleset.json.

I know that is can be done - as codes coming from LinterCop are being recognized and can be referenced in app.json or in ruleset.json.

It is not a biggie but it would be nice if we would have consistency there :)

Cheers

**Comment by vjekob** [comment]
I am not sure I really want to do it.

About suppressing warnings, why would you want to do that? Isn't it better to just switch Ninja off, because switching these warnings off essentially says "I don't care about my object ID conflicts", so why bothering with Ninja in the first place?

About escalating them to errors, or demoting them to infos, other than keeping them "consistent", I don't see much benefit.

About the consistency itself, not everything in AL is "consistent". Try adding an invalid key to app.json to trigger error AL0124, and then try demoting it to warning, and then suppressing it. You can't.

Potential object ID collision detected by Ninja is not a language issue. It's a development process issue.

If you can present a valid business case for this, where users would benefit from both having Ninja active and having Ninja's warnings suppressed (or promoted/demoted), I'll gladly reconsider. Until then, I'll close this case.

**Comment by TCI-Radek** [comment]
Well... working with a bigger group of developers with different background/experience/attitude you learn to not relay on their good will / perfect understanding of the rules which should be followed ;)
We try to keep our product warning-free and escalate warnings to errors - so no-one could check in poorly written code to main repo.
But like I said - it is not a biggie ;)

**Comment by vjekob** [comment]
This has been fully implemented and released as part of **version 3.3.0**.

N0301 now supports all three standard AL diagnostic control mechanisms:

- **AL Rulesets** — configure `al.ruleSetPath` and set the action for N0301 in your `.ruleset.json` (including recursive `includedRuleSets`)
- **`suppressWarnings` in `app.json`** — add `"N0301"` to suppress it globally
- **`#pragma warning disable/restore`** — suppress per-region in individual `.al` files

Diagnostics also re-evaluate live when `app.json` or ruleset files change.
